login:
    path: /authorization
    controller: App\Controller\AuthorizationController::index

registration:
  path: /registration
  controller: App\Controller\RegistrationController::index

user:
  path: /user
  controller: App\Controller\UserController::index